name: Deploy To Azure

on:
  push:
    branches:    
      - dev

jobs:
  create-azure-resources:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Storage Account
      uses: azure/CLI@v1
      env:
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        REGION: ${{ secrets.AZURE_REGION }}
      with:
        azcliversion: latest
        inlineScript: |
          az storage account create -n "$STORAGE_ACCOUNT_NAME" -g "$RESOURCE_GROUP" --sku Standard_LRS -l "$REGION"

  build-webapp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build
        working-directory: ./webapp
        run: |
          npm ci
          npm run build:ci

      - name: Store Website
        uses: actions/upload-artifact@v2
        with:
          name: static-webapp
          path: ./webapp/dist/
  deploy-webapp:
    needs: [build-webapp, create-azure-resources]
    runs-on: ubuntu-latest

    steps:
    - name: Get Website
      uses: actions/download-artifact@v2
      with:
        name: static-webapp

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Static Website
      uses: azure/CLI@v1
      env:
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob service-properties update --account-name "$STORAGE_ACCOUNT_NAME" --static-website --404-document "404.html" --index-document "index.html"
    
    - name: Upload Files
      uses: azure/CLI@v1
      env:
        STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob sync -s . -c '$web' --account-name "$STORAGE_ACCOUNT_NAME"
