name: Deploy To Azure

on:
  push:
    branches:    
      - dev

jobs:
  build-webapp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build
        working-directory: ./webapp
        run: |
          npm ci
          npm run build:ci

      - name: Store Website
        uses: actions/upload-artifact@v2
        with:
          name: static-webapp
          path: ./webapp/dist/
